-- Create ad_scrolls table
create table public.ad_scrolls (
  id bigint generated by default as identity primary key,
  image_url text not null,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.ad_scrolls enable row level security;

-- Policies
create policy "Public ads are viewable by everyone"
  on public.ad_scrolls for select
  using ( true );

create policy "Admins can insert ads"
  on public.ad_scrolls for insert
  with check ( auth.role() = 'authenticated' );

create policy "Admins can update ads"
  on public.ad_scrolls for update
  using ( auth.role() = 'authenticated' );

create policy "Admins can delete ads"
  on public.ad_scrolls for delete
  using ( auth.role() = 'authenticated' );

-- Insert default ads (legacy assets)
insert into public.ad_scrolls (image_url) values
('/legacy_assets/images/card1.png'),
('/legacy_assets/images/card2.png'),
('/legacy_assets/images/card3.png');
