-- Create notices table
create table public.notices (
  id bigint generated by default as identity primary key,
  text text not null,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.notices enable row level security;

-- Policies
create policy "Public notices are viewable by everyone"
  on public.notices for select
  using ( true );

create policy "Admins can insert notices"
  on public.notices for insert
  with check ( auth.role() = 'authenticated' ); -- Simplified for demo, ideally check admin role

create policy "Admins can update notices"
  on public.notices for update
  using ( auth.role() = 'authenticated' );

create policy "Admins can delete notices"
  on public.notices for delete
  using ( auth.role() = 'authenticated' );

-- Insert default notices
insert into public.notices (text) values
('📢 Free delivery on orders over $50!'),
('Fresh organic vegetables restocked daily at 8 AM.'),
('Use code FRESH20 for 20% off your first order.');
