-- Add banner_url to categories table
ALTER TABLE categories 
ADD COLUMN IF NOT EXISTS banner_url TEXT;

-- Ensure subcategories table exists (it should based on code, but good to be safe)
CREATE TABLE IF NOT EXISTS subcategories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id UUID REFERENCES categories(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Policy to allow admins to manage categories
CREATE POLICY "Admins can insert categories" ON categories FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Admins can update categories" ON categories FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can delete categories" ON categories FOR DELETE USING (auth.role() = 'authenticated');

CREATE POLICY "Admins can insert subcategories" ON subcategories FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Admins can update subcategories" ON subcategories FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can delete subcategories" ON subcategories FOR DELETE USING (auth.role() = 'authenticated');
