-- 1. Add 'is_hidden' column to categories table
-- This allows creating categories (like "Special Offers") that don't appear in the main navigation
ALTER TABLE categories 
ADD COLUMN IF NOT EXISTS is_hidden BOOLEAN DEFAULT FALSE;

-- 2. Create product_promotions table
-- This allows linking a product to a "Special" subcategory (e.g., "Flash Sales") 
-- with a specific discount percentage, independent of its main category.
CREATE TABLE IF NOT EXISTS product_promotions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    -- CORRECTED: Changed from BIGINT to UUID to match subcategories.id type
    promotion_subcategory_id UUID REFERENCES subcategories(id) ON DELETE CASCADE,
    discount_percent INTEGER NOT NULL CHECK (discount_percent >= 0 AND discount_percent <= 100),
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(product_id, promotion_subcategory_id)
);

-- Note: You will need to manually insert your Special Category and Subcategory.
-- Example Usage:
-- INSERT INTO categories (name, slug, image_url, is_hidden) VALUES ('Special Offers', 'special-offers', 'url', TRUE);
-- INSERT INTO subcategories (category_id, name) VALUES ((SELECT id FROM categories WHERE slug='special-offers'), 'Flash Sales');
-- INSERT INTO product_promotions (product_id, promotion_subcategory_id, discount_percent) VALUES (123, (SELECT id FROM subcategories WHERE name='Flash Sales'), 10);
