-- Special Categories V2
-- 1. Create table for special categories (tags)
CREATE TABLE IF NOT EXISTS special_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE, -- e.g., 'Flash Deal', 'Ramadan Offer', 'Weekly Sale'
    description TEXT,
    image_url TEXT, -- For Offer Slider
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Modify products table to support direct association and persistent pricing
-- Add FK to special_categories
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS special_category_id BIGINT REFERENCES special_categories(id) ON DELETE SET NULL;

-- Add discount_percent for display purposes (Badge)
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS discount_percent INTEGER DEFAULT 0;

-- NOTE: 'price' and 'original_price' columns already exist in 'products'.
-- Logic: 
-- When applying a discount:
-- 1. Move current 'price' to 'original_price'.
-- 2. Update 'price' to the new discounted value.
-- 3. Set 'discount_percent'.
-- 4. Set 'special_category_id'.

-- Example Implementation (for Admin Panel usage):
-- UPDATE products 
-- SET 
--   original_price = price, 
--   price = ROUND(price * 0.9), -- 10% off
--   discount_percent = 10,
--   special_category_id = (SELECT id FROM special_categories WHERE name = 'Flash Deal')
-- WHERE id = 123;
